### PR TITLE
Custom formatter should not need to require traceback (causes problems w...

### PR DESCRIPTION
**Pull request by ghost**
Addresses issue jb55/node-raw-stacktrace#2

### CODE REVIEW

**Comment by jb55** [comment]
:+1:

**Comment by aventuralabs** [comment]
Awesome, thanks!

**Comment by aventuralabs** [comment]
Can we get this updated in npm by chance? Looking to use for dependencies in mattrobenolt/raven-node

**Comment by jb55** [comment]
yup, version 1.0.0 was pushed

**Comment by aventuralabs** [comment]
Thank you much!

**Pull request merged**
